trigger:
  - main  # Change if your main branch has a different name

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Maven@3
    displayName: 'Build with Maven'
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11' # or '17' if your project needs it
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
